package:
  name: adorym-E
  version: '0.1.0'

source:
  git_url: https://github.com/rhoadesScholar/adorym-E.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - h5py
    - six
    - tifffile    
    - pandas
    - matplotlib
    - dxchange

test:
  # Python imports
  imports:
    - adorym

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
